#!/bin/sh

git diff-files --quiet || {
    git status -s
    echo -e "\nYou have uncommited changes."
    exit 1
}

cargo fmt --check -q || {
    echo -e "\nPlease format your code."
    exit 1
}

echo "PASSED: Format"

cargo clippy -q -- --deny warnings || {
    echo -e "\nClippy is angry."
    exit 1
}

echo "PASSED: Clippy"

cargo test -- --include-ignored || {
    echo -e "\nSome tests have failed"
    exit 1
}

echo "PASSED: Tests"
